### ISSUE TITLE
Error on value ?

### ISSUE THREAD

**Issue by o-Fred-o** [mseyne/superpowers-tutorials#1]
Hi,
On the chapter 2, in the Setting arcade bodies, you say :
"We then change for both paddles the size of x to 0.2 (size = 0.2, 0) "
i think the size is (0.2,1) , like in your screenshot.
Nice tutorial, thank you :+1: ,  i continue ...

**Comment by o-Fred-o** [comment]
On chapter 3,
the keyboard key values for the paddle 1 seems to be for Qwerty keyboard (W/S), but on chapther 4 in the menu scene they are (Z/S) like on Azerty ?

**Comment by o-Fred-o** [comment]
On chapter 4,
For the menu, the color of the info2 is 356ef1 and not f14735 :-)

**Comment by mseyne** [comment]
Thank you very much for the corrections o-Fred-o, I clean and push all this. :+1:  :smile: 
For the keyboard, yes I did a mistake because I use an Azerty keyboard, my initial idea was to do the tutorial for a Qwerty keyboard. (make me think that the game in project source is in Azerty too), I will do a change to stick to Qwerty.
